# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brito/Documents/lab/tensor-2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brito/Documents/lab/tensor-2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brito/Documents/lab/tensor-2/CMakeFiles /home/brito/Documents/lab/tensor-2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brito/Documents/lab/tensor-2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mimir_shaders

# Build rule for target.
mimir_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimir_shaders
.PHONY : mimir_shaders

# fast build rule for target.
mimir_shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_shaders.dir/build.make CMakeFiles/mimir_shaders.dir/build
.PHONY : mimir_shaders/fast

#=============================================================================
# Target rules for targets named mimir_core

# Build rule for target.
mimir_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimir_core
.PHONY : mimir_core

# fast build rule for target.
mimir_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/build
.PHONY : mimir_core/fast

#=============================================================================
# Target rules for targets named mimir

# Build rule for target.
mimir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimir
.PHONY : mimir

# fast build rule for target.
mimir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir.dir/build.make CMakeFiles/mimir.dir/build
.PHONY : mimir/fast

#=============================================================================
# Target rules for targets named appimage

# Build rule for target.
appimage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appimage
.PHONY : appimage

# fast build rule for target.
appimage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appimage.dir/build.make CMakeFiles/appimage.dir/build
.PHONY : appimage/fast

src/ConfigOverrides.o: src/ConfigOverrides.cpp.o
.PHONY : src/ConfigOverrides.o

# target to build an object file
src/ConfigOverrides.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/ConfigOverrides.cpp.o
.PHONY : src/ConfigOverrides.cpp.o

src/ConfigOverrides.i: src/ConfigOverrides.cpp.i
.PHONY : src/ConfigOverrides.i

# target to preprocess a source file
src/ConfigOverrides.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/ConfigOverrides.cpp.i
.PHONY : src/ConfigOverrides.cpp.i

src/ConfigOverrides.s: src/ConfigOverrides.cpp.s
.PHONY : src/ConfigOverrides.s

# target to generate assembly for a file
src/ConfigOverrides.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/ConfigOverrides.cpp.s
.PHONY : src/ConfigOverrides.cpp.s

src/Encoder.o: src/Encoder.cpp.o
.PHONY : src/Encoder.o

# target to build an object file
src/Encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Encoder.cpp.o
.PHONY : src/Encoder.cpp.o

src/Encoder.i: src/Encoder.cpp.i
.PHONY : src/Encoder.i

# target to preprocess a source file
src/Encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Encoder.cpp.i
.PHONY : src/Encoder.cpp.i

src/Encoder.s: src/Encoder.cpp.s
.PHONY : src/Encoder.s

# target to generate assembly for a file
src/Encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Encoder.cpp.s
.PHONY : src/Encoder.cpp.s

src/Helpers.o: src/Helpers.cpp.o
.PHONY : src/Helpers.o

# target to build an object file
src/Helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Helpers.cpp.o
.PHONY : src/Helpers.cpp.o

src/Helpers.i: src/Helpers.cpp.i
.PHONY : src/Helpers.i

# target to preprocess a source file
src/Helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Helpers.cpp.i
.PHONY : src/Helpers.cpp.i

src/Helpers.s: src/Helpers.cpp.s
.PHONY : src/Helpers.s

# target to generate assembly for a file
src/Helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Helpers.cpp.s
.PHONY : src/Helpers.cpp.s

src/Model.o: src/Model.cpp.o
.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Models/Diffusion/CondDiffusionModel.o: src/Models/Diffusion/CondDiffusionModel.cpp.o
.PHONY : src/Models/Diffusion/CondDiffusionModel.o

# target to build an object file
src/Models/Diffusion/CondDiffusionModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/CondDiffusionModel.cpp.o
.PHONY : src/Models/Diffusion/CondDiffusionModel.cpp.o

src/Models/Diffusion/CondDiffusionModel.i: src/Models/Diffusion/CondDiffusionModel.cpp.i
.PHONY : src/Models/Diffusion/CondDiffusionModel.i

# target to preprocess a source file
src/Models/Diffusion/CondDiffusionModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/CondDiffusionModel.cpp.i
.PHONY : src/Models/Diffusion/CondDiffusionModel.cpp.i

src/Models/Diffusion/CondDiffusionModel.s: src/Models/Diffusion/CondDiffusionModel.cpp.s
.PHONY : src/Models/Diffusion/CondDiffusionModel.s

# target to generate assembly for a file
src/Models/Diffusion/CondDiffusionModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/CondDiffusionModel.cpp.s
.PHONY : src/Models/Diffusion/CondDiffusionModel.cpp.s

src/Models/Diffusion/DiffusionModel.o: src/Models/Diffusion/DiffusionModel.cpp.o
.PHONY : src/Models/Diffusion/DiffusionModel.o

# target to build an object file
src/Models/Diffusion/DiffusionModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/DiffusionModel.cpp.o
.PHONY : src/Models/Diffusion/DiffusionModel.cpp.o

src/Models/Diffusion/DiffusionModel.i: src/Models/Diffusion/DiffusionModel.cpp.i
.PHONY : src/Models/Diffusion/DiffusionModel.i

# target to preprocess a source file
src/Models/Diffusion/DiffusionModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/DiffusionModel.cpp.i
.PHONY : src/Models/Diffusion/DiffusionModel.cpp.i

src/Models/Diffusion/DiffusionModel.s: src/Models/Diffusion/DiffusionModel.cpp.s
.PHONY : src/Models/Diffusion/DiffusionModel.s

# target to generate assembly for a file
src/Models/Diffusion/DiffusionModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/DiffusionModel.cpp.s
.PHONY : src/Models/Diffusion/DiffusionModel.cpp.s

src/Models/Diffusion/HFSDXLTransformerBlockModel.o: src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.o
.PHONY : src/Models/Diffusion/HFSDXLTransformerBlockModel.o

# target to build an object file
src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.o
.PHONY : src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.o

src/Models/Diffusion/HFSDXLTransformerBlockModel.i: src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.i
.PHONY : src/Models/Diffusion/HFSDXLTransformerBlockModel.i

# target to preprocess a source file
src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.i
.PHONY : src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.i

src/Models/Diffusion/HFSDXLTransformerBlockModel.s: src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.s
.PHONY : src/Models/Diffusion/HFSDXLTransformerBlockModel.s

# target to generate assembly for a file
src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.s
.PHONY : src/Models/Diffusion/HFSDXLTransformerBlockModel.cpp.s

src/Models/Diffusion/LumenLatentDiffusionModel.o: src/Models/Diffusion/LumenLatentDiffusionModel.cpp.o
.PHONY : src/Models/Diffusion/LumenLatentDiffusionModel.o

# target to build an object file
src/Models/Diffusion/LumenLatentDiffusionModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/LumenLatentDiffusionModel.cpp.o
.PHONY : src/Models/Diffusion/LumenLatentDiffusionModel.cpp.o

src/Models/Diffusion/LumenLatentDiffusionModel.i: src/Models/Diffusion/LumenLatentDiffusionModel.cpp.i
.PHONY : src/Models/Diffusion/LumenLatentDiffusionModel.i

# target to preprocess a source file
src/Models/Diffusion/LumenLatentDiffusionModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/LumenLatentDiffusionModel.cpp.i
.PHONY : src/Models/Diffusion/LumenLatentDiffusionModel.cpp.i

src/Models/Diffusion/LumenLatentDiffusionModel.s: src/Models/Diffusion/LumenLatentDiffusionModel.cpp.s
.PHONY : src/Models/Diffusion/LumenLatentDiffusionModel.s

# target to generate assembly for a file
src/Models/Diffusion/LumenLatentDiffusionModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/LumenLatentDiffusionModel.cpp.s
.PHONY : src/Models/Diffusion/LumenLatentDiffusionModel.cpp.s

src/Models/Diffusion/SD35Model.o: src/Models/Diffusion/SD35Model.cpp.o
.PHONY : src/Models/Diffusion/SD35Model.o

# target to build an object file
src/Models/Diffusion/SD35Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/SD35Model.cpp.o
.PHONY : src/Models/Diffusion/SD35Model.cpp.o

src/Models/Diffusion/SD35Model.i: src/Models/Diffusion/SD35Model.cpp.i
.PHONY : src/Models/Diffusion/SD35Model.i

# target to preprocess a source file
src/Models/Diffusion/SD35Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/SD35Model.cpp.i
.PHONY : src/Models/Diffusion/SD35Model.cpp.i

src/Models/Diffusion/SD35Model.s: src/Models/Diffusion/SD35Model.cpp.s
.PHONY : src/Models/Diffusion/SD35Model.s

# target to generate assembly for a file
src/Models/Diffusion/SD35Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Diffusion/SD35Model.cpp.s
.PHONY : src/Models/Diffusion/SD35Model.cpp.s

src/Models/External/ExternalSafeTensorsModel.o: src/Models/External/ExternalSafeTensorsModel.cpp.o
.PHONY : src/Models/External/ExternalSafeTensorsModel.o

# target to build an object file
src/Models/External/ExternalSafeTensorsModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/External/ExternalSafeTensorsModel.cpp.o
.PHONY : src/Models/External/ExternalSafeTensorsModel.cpp.o

src/Models/External/ExternalSafeTensorsModel.i: src/Models/External/ExternalSafeTensorsModel.cpp.i
.PHONY : src/Models/External/ExternalSafeTensorsModel.i

# target to preprocess a source file
src/Models/External/ExternalSafeTensorsModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/External/ExternalSafeTensorsModel.cpp.i
.PHONY : src/Models/External/ExternalSafeTensorsModel.cpp.i

src/Models/External/ExternalSafeTensorsModel.s: src/Models/External/ExternalSafeTensorsModel.cpp.s
.PHONY : src/Models/External/ExternalSafeTensorsModel.s

# target to generate assembly for a file
src/Models/External/ExternalSafeTensorsModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/External/ExternalSafeTensorsModel.cpp.s
.PHONY : src/Models/External/ExternalSafeTensorsModel.cpp.s

src/Models/MLP/BasicMLPModel.o: src/Models/MLP/BasicMLPModel.cpp.o
.PHONY : src/Models/MLP/BasicMLPModel.o

# target to build an object file
src/Models/MLP/BasicMLPModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/MLP/BasicMLPModel.cpp.o
.PHONY : src/Models/MLP/BasicMLPModel.cpp.o

src/Models/MLP/BasicMLPModel.i: src/Models/MLP/BasicMLPModel.cpp.i
.PHONY : src/Models/MLP/BasicMLPModel.i

# target to preprocess a source file
src/Models/MLP/BasicMLPModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/MLP/BasicMLPModel.cpp.i
.PHONY : src/Models/MLP/BasicMLPModel.cpp.i

src/Models/MLP/BasicMLPModel.s: src/Models/MLP/BasicMLPModel.cpp.s
.PHONY : src/Models/MLP/BasicMLPModel.s

# target to generate assembly for a file
src/Models/MLP/BasicMLPModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/MLP/BasicMLPModel.cpp.s
.PHONY : src/Models/MLP/BasicMLPModel.cpp.s

src/Models/NLP/CausalLMModel.o: src/Models/NLP/CausalLMModel.cpp.o
.PHONY : src/Models/NLP/CausalLMModel.o

# target to build an object file
src/Models/NLP/CausalLMModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/CausalLMModel.cpp.o
.PHONY : src/Models/NLP/CausalLMModel.cpp.o

src/Models/NLP/CausalLMModel.i: src/Models/NLP/CausalLMModel.cpp.i
.PHONY : src/Models/NLP/CausalLMModel.i

# target to preprocess a source file
src/Models/NLP/CausalLMModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/CausalLMModel.cpp.i
.PHONY : src/Models/NLP/CausalLMModel.cpp.i

src/Models/NLP/CausalLMModel.s: src/Models/NLP/CausalLMModel.cpp.s
.PHONY : src/Models/NLP/CausalLMModel.s

# target to generate assembly for a file
src/Models/NLP/CausalLMModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/CausalLMModel.cpp.s
.PHONY : src/Models/NLP/CausalLMModel.cpp.s

src/Models/NLP/HFCLIPTextEncoder1Model.o: src/Models/NLP/HFCLIPTextEncoder1Model.cpp.o
.PHONY : src/Models/NLP/HFCLIPTextEncoder1Model.o

# target to build an object file
src/Models/NLP/HFCLIPTextEncoder1Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/HFCLIPTextEncoder1Model.cpp.o
.PHONY : src/Models/NLP/HFCLIPTextEncoder1Model.cpp.o

src/Models/NLP/HFCLIPTextEncoder1Model.i: src/Models/NLP/HFCLIPTextEncoder1Model.cpp.i
.PHONY : src/Models/NLP/HFCLIPTextEncoder1Model.i

# target to preprocess a source file
src/Models/NLP/HFCLIPTextEncoder1Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/HFCLIPTextEncoder1Model.cpp.i
.PHONY : src/Models/NLP/HFCLIPTextEncoder1Model.cpp.i

src/Models/NLP/HFCLIPTextEncoder1Model.s: src/Models/NLP/HFCLIPTextEncoder1Model.cpp.s
.PHONY : src/Models/NLP/HFCLIPTextEncoder1Model.s

# target to generate assembly for a file
src/Models/NLP/HFCLIPTextEncoder1Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/HFCLIPTextEncoder1Model.cpp.s
.PHONY : src/Models/NLP/HFCLIPTextEncoder1Model.cpp.s

src/Models/NLP/HFCLIPTextEncoder2Model.o: src/Models/NLP/HFCLIPTextEncoder2Model.cpp.o
.PHONY : src/Models/NLP/HFCLIPTextEncoder2Model.o

# target to build an object file
src/Models/NLP/HFCLIPTextEncoder2Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/HFCLIPTextEncoder2Model.cpp.o
.PHONY : src/Models/NLP/HFCLIPTextEncoder2Model.cpp.o

src/Models/NLP/HFCLIPTextEncoder2Model.i: src/Models/NLP/HFCLIPTextEncoder2Model.cpp.i
.PHONY : src/Models/NLP/HFCLIPTextEncoder2Model.i

# target to preprocess a source file
src/Models/NLP/HFCLIPTextEncoder2Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/HFCLIPTextEncoder2Model.cpp.i
.PHONY : src/Models/NLP/HFCLIPTextEncoder2Model.cpp.i

src/Models/NLP/HFCLIPTextEncoder2Model.s: src/Models/NLP/HFCLIPTextEncoder2Model.cpp.s
.PHONY : src/Models/NLP/HFCLIPTextEncoder2Model.s

# target to generate assembly for a file
src/Models/NLP/HFCLIPTextEncoder2Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/HFCLIPTextEncoder2Model.cpp.s
.PHONY : src/Models/NLP/HFCLIPTextEncoder2Model.cpp.s

src/Models/NLP/TransformerModel.o: src/Models/NLP/TransformerModel.cpp.o
.PHONY : src/Models/NLP/TransformerModel.o

# target to build an object file
src/Models/NLP/TransformerModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/TransformerModel.cpp.o
.PHONY : src/Models/NLP/TransformerModel.cpp.o

src/Models/NLP/TransformerModel.i: src/Models/NLP/TransformerModel.cpp.i
.PHONY : src/Models/NLP/TransformerModel.i

# target to preprocess a source file
src/Models/NLP/TransformerModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/TransformerModel.cpp.i
.PHONY : src/Models/NLP/TransformerModel.cpp.i

src/Models/NLP/TransformerModel.s: src/Models/NLP/TransformerModel.cpp.s
.PHONY : src/Models/NLP/TransformerModel.s

# target to generate assembly for a file
src/Models/NLP/TransformerModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/TransformerModel.cpp.s
.PHONY : src/Models/NLP/TransformerModel.cpp.s

src/Models/NLP/VAETextModel.o: src/Models/NLP/VAETextModel.cpp.o
.PHONY : src/Models/NLP/VAETextModel.o

# target to build an object file
src/Models/NLP/VAETextModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/VAETextModel.cpp.o
.PHONY : src/Models/NLP/VAETextModel.cpp.o

src/Models/NLP/VAETextModel.i: src/Models/NLP/VAETextModel.cpp.i
.PHONY : src/Models/NLP/VAETextModel.i

# target to preprocess a source file
src/Models/NLP/VAETextModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/VAETextModel.cpp.i
.PHONY : src/Models/NLP/VAETextModel.cpp.i

src/Models/NLP/VAETextModel.s: src/Models/NLP/VAETextModel.cpp.s
.PHONY : src/Models/NLP/VAETextModel.s

# target to generate assembly for a file
src/Models/NLP/VAETextModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/NLP/VAETextModel.cpp.s
.PHONY : src/Models/NLP/VAETextModel.cpp.s

src/Models/Registry/ModelArchitectures.o: src/Models/Registry/ModelArchitectures.cpp.o
.PHONY : src/Models/Registry/ModelArchitectures.o

# target to build an object file
src/Models/Registry/ModelArchitectures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Registry/ModelArchitectures.cpp.o
.PHONY : src/Models/Registry/ModelArchitectures.cpp.o

src/Models/Registry/ModelArchitectures.i: src/Models/Registry/ModelArchitectures.cpp.i
.PHONY : src/Models/Registry/ModelArchitectures.i

# target to preprocess a source file
src/Models/Registry/ModelArchitectures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Registry/ModelArchitectures.cpp.i
.PHONY : src/Models/Registry/ModelArchitectures.cpp.i

src/Models/Registry/ModelArchitectures.s: src/Models/Registry/ModelArchitectures.cpp.s
.PHONY : src/Models/Registry/ModelArchitectures.s

# target to generate assembly for a file
src/Models/Registry/ModelArchitectures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Registry/ModelArchitectures.cpp.s
.PHONY : src/Models/Registry/ModelArchitectures.cpp.s

src/Models/Vision/CNN/MobileNetModel.o: src/Models/Vision/CNN/MobileNetModel.cpp.o
.PHONY : src/Models/Vision/CNN/MobileNetModel.o

# target to build an object file
src/Models/Vision/CNN/MobileNetModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/MobileNetModel.cpp.o
.PHONY : src/Models/Vision/CNN/MobileNetModel.cpp.o

src/Models/Vision/CNN/MobileNetModel.i: src/Models/Vision/CNN/MobileNetModel.cpp.i
.PHONY : src/Models/Vision/CNN/MobileNetModel.i

# target to preprocess a source file
src/Models/Vision/CNN/MobileNetModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/MobileNetModel.cpp.i
.PHONY : src/Models/Vision/CNN/MobileNetModel.cpp.i

src/Models/Vision/CNN/MobileNetModel.s: src/Models/Vision/CNN/MobileNetModel.cpp.s
.PHONY : src/Models/Vision/CNN/MobileNetModel.s

# target to generate assembly for a file
src/Models/Vision/CNN/MobileNetModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/MobileNetModel.cpp.s
.PHONY : src/Models/Vision/CNN/MobileNetModel.cpp.s

src/Models/Vision/CNN/ResNetModel.o: src/Models/Vision/CNN/ResNetModel.cpp.o
.PHONY : src/Models/Vision/CNN/ResNetModel.o

# target to build an object file
src/Models/Vision/CNN/ResNetModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/ResNetModel.cpp.o
.PHONY : src/Models/Vision/CNN/ResNetModel.cpp.o

src/Models/Vision/CNN/ResNetModel.i: src/Models/Vision/CNN/ResNetModel.cpp.i
.PHONY : src/Models/Vision/CNN/ResNetModel.i

# target to preprocess a source file
src/Models/Vision/CNN/ResNetModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/ResNetModel.cpp.i
.PHONY : src/Models/Vision/CNN/ResNetModel.cpp.i

src/Models/Vision/CNN/ResNetModel.s: src/Models/Vision/CNN/ResNetModel.cpp.s
.PHONY : src/Models/Vision/CNN/ResNetModel.s

# target to generate assembly for a file
src/Models/Vision/CNN/ResNetModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/ResNetModel.cpp.s
.PHONY : src/Models/Vision/CNN/ResNetModel.cpp.s

src/Models/Vision/CNN/VGG16FeatModel.o: src/Models/Vision/CNN/VGG16FeatModel.cpp.o
.PHONY : src/Models/Vision/CNN/VGG16FeatModel.o

# target to build an object file
src/Models/Vision/CNN/VGG16FeatModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG16FeatModel.cpp.o
.PHONY : src/Models/Vision/CNN/VGG16FeatModel.cpp.o

src/Models/Vision/CNN/VGG16FeatModel.i: src/Models/Vision/CNN/VGG16FeatModel.cpp.i
.PHONY : src/Models/Vision/CNN/VGG16FeatModel.i

# target to preprocess a source file
src/Models/Vision/CNN/VGG16FeatModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG16FeatModel.cpp.i
.PHONY : src/Models/Vision/CNN/VGG16FeatModel.cpp.i

src/Models/Vision/CNN/VGG16FeatModel.s: src/Models/Vision/CNN/VGG16FeatModel.cpp.s
.PHONY : src/Models/Vision/CNN/VGG16FeatModel.s

# target to generate assembly for a file
src/Models/Vision/CNN/VGG16FeatModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG16FeatModel.cpp.s
.PHONY : src/Models/Vision/CNN/VGG16FeatModel.cpp.s

src/Models/Vision/CNN/VGG16Model.o: src/Models/Vision/CNN/VGG16Model.cpp.o
.PHONY : src/Models/Vision/CNN/VGG16Model.o

# target to build an object file
src/Models/Vision/CNN/VGG16Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG16Model.cpp.o
.PHONY : src/Models/Vision/CNN/VGG16Model.cpp.o

src/Models/Vision/CNN/VGG16Model.i: src/Models/Vision/CNN/VGG16Model.cpp.i
.PHONY : src/Models/Vision/CNN/VGG16Model.i

# target to preprocess a source file
src/Models/Vision/CNN/VGG16Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG16Model.cpp.i
.PHONY : src/Models/Vision/CNN/VGG16Model.cpp.i

src/Models/Vision/CNN/VGG16Model.s: src/Models/Vision/CNN/VGG16Model.cpp.s
.PHONY : src/Models/Vision/CNN/VGG16Model.s

# target to generate assembly for a file
src/Models/Vision/CNN/VGG16Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG16Model.cpp.s
.PHONY : src/Models/Vision/CNN/VGG16Model.cpp.s

src/Models/Vision/CNN/VGG19Model.o: src/Models/Vision/CNN/VGG19Model.cpp.o
.PHONY : src/Models/Vision/CNN/VGG19Model.o

# target to build an object file
src/Models/Vision/CNN/VGG19Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG19Model.cpp.o
.PHONY : src/Models/Vision/CNN/VGG19Model.cpp.o

src/Models/Vision/CNN/VGG19Model.i: src/Models/Vision/CNN/VGG19Model.cpp.i
.PHONY : src/Models/Vision/CNN/VGG19Model.i

# target to preprocess a source file
src/Models/Vision/CNN/VGG19Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG19Model.cpp.i
.PHONY : src/Models/Vision/CNN/VGG19Model.cpp.i

src/Models/Vision/CNN/VGG19Model.s: src/Models/Vision/CNN/VGG19Model.cpp.s
.PHONY : src/Models/Vision/CNN/VGG19Model.s

# target to generate assembly for a file
src/Models/Vision/CNN/VGG19Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/CNN/VGG19Model.cpp.s
.PHONY : src/Models/Vision/CNN/VGG19Model.cpp.s

src/Models/Vision/GanLatentModel.o: src/Models/Vision/GanLatentModel.cpp.o
.PHONY : src/Models/Vision/GanLatentModel.o

# target to build an object file
src/Models/Vision/GanLatentModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/GanLatentModel.cpp.o
.PHONY : src/Models/Vision/GanLatentModel.cpp.o

src/Models/Vision/GanLatentModel.i: src/Models/Vision/GanLatentModel.cpp.i
.PHONY : src/Models/Vision/GanLatentModel.i

# target to preprocess a source file
src/Models/Vision/GanLatentModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/GanLatentModel.cpp.i
.PHONY : src/Models/Vision/GanLatentModel.cpp.i

src/Models/Vision/GanLatentModel.s: src/Models/Vision/GanLatentModel.cpp.s
.PHONY : src/Models/Vision/GanLatentModel.s

# target to generate assembly for a file
src/Models/Vision/GanLatentModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/GanLatentModel.cpp.s
.PHONY : src/Models/Vision/GanLatentModel.cpp.s

src/Models/Vision/HFVaeDecoderModel.o: src/Models/Vision/HFVaeDecoderModel.cpp.o
.PHONY : src/Models/Vision/HFVaeDecoderModel.o

# target to build an object file
src/Models/Vision/HFVaeDecoderModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/HFVaeDecoderModel.cpp.o
.PHONY : src/Models/Vision/HFVaeDecoderModel.cpp.o

src/Models/Vision/HFVaeDecoderModel.i: src/Models/Vision/HFVaeDecoderModel.cpp.i
.PHONY : src/Models/Vision/HFVaeDecoderModel.i

# target to preprocess a source file
src/Models/Vision/HFVaeDecoderModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/HFVaeDecoderModel.cpp.i
.PHONY : src/Models/Vision/HFVaeDecoderModel.cpp.i

src/Models/Vision/HFVaeDecoderModel.s: src/Models/Vision/HFVaeDecoderModel.cpp.s
.PHONY : src/Models/Vision/HFVaeDecoderModel.s

# target to generate assembly for a file
src/Models/Vision/HFVaeDecoderModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/HFVaeDecoderModel.cpp.s
.PHONY : src/Models/Vision/HFVaeDecoderModel.cpp.s

src/Models/Vision/PatchDiscriminatorModel.o: src/Models/Vision/PatchDiscriminatorModel.cpp.o
.PHONY : src/Models/Vision/PatchDiscriminatorModel.o

# target to build an object file
src/Models/Vision/PatchDiscriminatorModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/PatchDiscriminatorModel.cpp.o
.PHONY : src/Models/Vision/PatchDiscriminatorModel.cpp.o

src/Models/Vision/PatchDiscriminatorModel.i: src/Models/Vision/PatchDiscriminatorModel.cpp.i
.PHONY : src/Models/Vision/PatchDiscriminatorModel.i

# target to preprocess a source file
src/Models/Vision/PatchDiscriminatorModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/PatchDiscriminatorModel.cpp.i
.PHONY : src/Models/Vision/PatchDiscriminatorModel.cpp.i

src/Models/Vision/PatchDiscriminatorModel.s: src/Models/Vision/PatchDiscriminatorModel.cpp.s
.PHONY : src/Models/Vision/PatchDiscriminatorModel.s

# target to generate assembly for a file
src/Models/Vision/PatchDiscriminatorModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/PatchDiscriminatorModel.cpp.s
.PHONY : src/Models/Vision/PatchDiscriminatorModel.cpp.s

src/Models/Vision/UNetModel.o: src/Models/Vision/UNetModel.cpp.o
.PHONY : src/Models/Vision/UNetModel.o

# target to build an object file
src/Models/Vision/UNetModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/UNetModel.cpp.o
.PHONY : src/Models/Vision/UNetModel.cpp.o

src/Models/Vision/UNetModel.i: src/Models/Vision/UNetModel.cpp.i
.PHONY : src/Models/Vision/UNetModel.i

# target to preprocess a source file
src/Models/Vision/UNetModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/UNetModel.cpp.i
.PHONY : src/Models/Vision/UNetModel.cpp.i

src/Models/Vision/UNetModel.s: src/Models/Vision/UNetModel.cpp.s
.PHONY : src/Models/Vision/UNetModel.s

# target to generate assembly for a file
src/Models/Vision/UNetModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/UNetModel.cpp.s
.PHONY : src/Models/Vision/UNetModel.cpp.s

src/Models/Vision/VAEConvModel.o: src/Models/Vision/VAEConvModel.cpp.o
.PHONY : src/Models/Vision/VAEConvModel.o

# target to build an object file
src/Models/Vision/VAEConvModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/VAEConvModel.cpp.o
.PHONY : src/Models/Vision/VAEConvModel.cpp.o

src/Models/Vision/VAEConvModel.i: src/Models/Vision/VAEConvModel.cpp.i
.PHONY : src/Models/Vision/VAEConvModel.i

# target to preprocess a source file
src/Models/Vision/VAEConvModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/VAEConvModel.cpp.i
.PHONY : src/Models/Vision/VAEConvModel.cpp.i

src/Models/Vision/VAEConvModel.s: src/Models/Vision/VAEConvModel.cpp.s
.PHONY : src/Models/Vision/VAEConvModel.s

# target to generate assembly for a file
src/Models/Vision/VAEConvModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/VAEConvModel.cpp.s
.PHONY : src/Models/Vision/VAEConvModel.cpp.s

src/Models/Vision/VAEModel.o: src/Models/Vision/VAEModel.cpp.o
.PHONY : src/Models/Vision/VAEModel.o

# target to build an object file
src/Models/Vision/VAEModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/VAEModel.cpp.o
.PHONY : src/Models/Vision/VAEModel.cpp.o

src/Models/Vision/VAEModel.i: src/Models/Vision/VAEModel.cpp.i
.PHONY : src/Models/Vision/VAEModel.i

# target to preprocess a source file
src/Models/Vision/VAEModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/VAEModel.cpp.i
.PHONY : src/Models/Vision/VAEModel.cpp.i

src/Models/Vision/VAEModel.s: src/Models/Vision/VAEModel.cpp.s
.PHONY : src/Models/Vision/VAEModel.s

# target to generate assembly for a file
src/Models/Vision/VAEModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/VAEModel.cpp.s
.PHONY : src/Models/Vision/VAEModel.cpp.s

src/Models/Vision/ViTModel.o: src/Models/Vision/ViTModel.cpp.o
.PHONY : src/Models/Vision/ViTModel.o

# target to build an object file
src/Models/Vision/ViTModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/ViTModel.cpp.o
.PHONY : src/Models/Vision/ViTModel.cpp.o

src/Models/Vision/ViTModel.i: src/Models/Vision/ViTModel.cpp.i
.PHONY : src/Models/Vision/ViTModel.i

# target to preprocess a source file
src/Models/Vision/ViTModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/ViTModel.cpp.i
.PHONY : src/Models/Vision/ViTModel.cpp.i

src/Models/Vision/ViTModel.s: src/Models/Vision/ViTModel.cpp.s
.PHONY : src/Models/Vision/ViTModel.s

# target to generate assembly for a file
src/Models/Vision/ViTModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Models/Vision/ViTModel.cpp.s
.PHONY : src/Models/Vision/ViTModel.cpp.s

src/Serialization/DebugJsonDump.o: src/Serialization/DebugJsonDump.cpp.o
.PHONY : src/Serialization/DebugJsonDump.o

# target to build an object file
src/Serialization/DebugJsonDump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/DebugJsonDump.cpp.o
.PHONY : src/Serialization/DebugJsonDump.cpp.o

src/Serialization/DebugJsonDump.i: src/Serialization/DebugJsonDump.cpp.i
.PHONY : src/Serialization/DebugJsonDump.i

# target to preprocess a source file
src/Serialization/DebugJsonDump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/DebugJsonDump.cpp.i
.PHONY : src/Serialization/DebugJsonDump.cpp.i

src/Serialization/DebugJsonDump.s: src/Serialization/DebugJsonDump.cpp.s
.PHONY : src/Serialization/DebugJsonDump.s

# target to generate assembly for a file
src/Serialization/DebugJsonDump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/DebugJsonDump.cpp.s
.PHONY : src/Serialization/DebugJsonDump.cpp.s

src/Serialization/RawCheckpointReader.o: src/Serialization/RawCheckpointReader.cpp.o
.PHONY : src/Serialization/RawCheckpointReader.o

# target to build an object file
src/Serialization/RawCheckpointReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/RawCheckpointReader.cpp.o
.PHONY : src/Serialization/RawCheckpointReader.cpp.o

src/Serialization/RawCheckpointReader.i: src/Serialization/RawCheckpointReader.cpp.i
.PHONY : src/Serialization/RawCheckpointReader.i

# target to preprocess a source file
src/Serialization/RawCheckpointReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/RawCheckpointReader.cpp.i
.PHONY : src/Serialization/RawCheckpointReader.cpp.i

src/Serialization/RawCheckpointReader.s: src/Serialization/RawCheckpointReader.cpp.s
.PHONY : src/Serialization/RawCheckpointReader.s

# target to generate assembly for a file
src/Serialization/RawCheckpointReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/RawCheckpointReader.cpp.s
.PHONY : src/Serialization/RawCheckpointReader.cpp.s

src/Serialization/RawCheckpointWriter.o: src/Serialization/RawCheckpointWriter.cpp.o
.PHONY : src/Serialization/RawCheckpointWriter.o

# target to build an object file
src/Serialization/RawCheckpointWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/RawCheckpointWriter.cpp.o
.PHONY : src/Serialization/RawCheckpointWriter.cpp.o

src/Serialization/RawCheckpointWriter.i: src/Serialization/RawCheckpointWriter.cpp.i
.PHONY : src/Serialization/RawCheckpointWriter.i

# target to preprocess a source file
src/Serialization/RawCheckpointWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/RawCheckpointWriter.cpp.i
.PHONY : src/Serialization/RawCheckpointWriter.cpp.i

src/Serialization/RawCheckpointWriter.s: src/Serialization/RawCheckpointWriter.cpp.s
.PHONY : src/Serialization/RawCheckpointWriter.s

# target to generate assembly for a file
src/Serialization/RawCheckpointWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/RawCheckpointWriter.cpp.s
.PHONY : src/Serialization/RawCheckpointWriter.cpp.s

src/Serialization/SafeTensorsReader.o: src/Serialization/SafeTensorsReader.cpp.o
.PHONY : src/Serialization/SafeTensorsReader.o

# target to build an object file
src/Serialization/SafeTensorsReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/SafeTensorsReader.cpp.o
.PHONY : src/Serialization/SafeTensorsReader.cpp.o

src/Serialization/SafeTensorsReader.i: src/Serialization/SafeTensorsReader.cpp.i
.PHONY : src/Serialization/SafeTensorsReader.i

# target to preprocess a source file
src/Serialization/SafeTensorsReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/SafeTensorsReader.cpp.i
.PHONY : src/Serialization/SafeTensorsReader.cpp.i

src/Serialization/SafeTensorsReader.s: src/Serialization/SafeTensorsReader.cpp.s
.PHONY : src/Serialization/SafeTensorsReader.s

# target to generate assembly for a file
src/Serialization/SafeTensorsReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/SafeTensorsReader.cpp.s
.PHONY : src/Serialization/SafeTensorsReader.cpp.s

src/Serialization/SafeTensorsWriter.o: src/Serialization/SafeTensorsWriter.cpp.o
.PHONY : src/Serialization/SafeTensorsWriter.o

# target to build an object file
src/Serialization/SafeTensorsWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/SafeTensorsWriter.cpp.o
.PHONY : src/Serialization/SafeTensorsWriter.cpp.o

src/Serialization/SafeTensorsWriter.i: src/Serialization/SafeTensorsWriter.cpp.i
.PHONY : src/Serialization/SafeTensorsWriter.i

# target to preprocess a source file
src/Serialization/SafeTensorsWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/SafeTensorsWriter.cpp.i
.PHONY : src/Serialization/SafeTensorsWriter.cpp.i

src/Serialization/SafeTensorsWriter.s: src/Serialization/SafeTensorsWriter.cpp.s
.PHONY : src/Serialization/SafeTensorsWriter.s

# target to generate assembly for a file
src/Serialization/SafeTensorsWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/SafeTensorsWriter.cpp.s
.PHONY : src/Serialization/SafeTensorsWriter.cpp.s

src/Serialization/Serialization.o: src/Serialization/Serialization.cpp.o
.PHONY : src/Serialization/Serialization.o

# target to build an object file
src/Serialization/Serialization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/Serialization.cpp.o
.PHONY : src/Serialization/Serialization.cpp.o

src/Serialization/Serialization.i: src/Serialization/Serialization.cpp.i
.PHONY : src/Serialization/Serialization.i

# target to preprocess a source file
src/Serialization/Serialization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/Serialization.cpp.i
.PHONY : src/Serialization/Serialization.cpp.i

src/Serialization/Serialization.s: src/Serialization/Serialization.cpp.s
.PHONY : src/Serialization/Serialization.s

# target to generate assembly for a file
src/Serialization/Serialization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Serialization/Serialization.cpp.s
.PHONY : src/Serialization/Serialization.cpp.s

src/Sha256.o: src/Sha256.cpp.o
.PHONY : src/Sha256.o

# target to build an object file
src/Sha256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Sha256.cpp.o
.PHONY : src/Sha256.cpp.o

src/Sha256.i: src/Sha256.cpp.i
.PHONY : src/Sha256.i

# target to preprocess a source file
src/Sha256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Sha256.cpp.i
.PHONY : src/Sha256.cpp.i

src/Sha256.s: src/Sha256.cpp.s
.PHONY : src/Sha256.s

# target to generate assembly for a file
src/Sha256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Sha256.cpp.s
.PHONY : src/Sha256.cpp.s

src/Tokenizer.o: src/Tokenizer.cpp.o
.PHONY : src/Tokenizer.o

# target to build an object file
src/Tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Tokenizer.cpp.o
.PHONY : src/Tokenizer.cpp.o

src/Tokenizer.i: src/Tokenizer.cpp.i
.PHONY : src/Tokenizer.i

# target to preprocess a source file
src/Tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Tokenizer.cpp.i
.PHONY : src/Tokenizer.cpp.i

src/Tokenizer.s: src/Tokenizer.cpp.s
.PHONY : src/Tokenizer.s

# target to generate assembly for a file
src/Tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Tokenizer.cpp.s
.PHONY : src/Tokenizer.cpp.s

src/Visualizer.o: src/Visualizer.cpp.o
.PHONY : src/Visualizer.o

# target to build an object file
src/Visualizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Visualizer.cpp.o
.PHONY : src/Visualizer.cpp.o

src/Visualizer.i: src/Visualizer.cpp.i
.PHONY : src/Visualizer.i

# target to preprocess a source file
src/Visualizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Visualizer.cpp.i
.PHONY : src/Visualizer.cpp.i

src/Visualizer.s: src/Visualizer.cpp.s
.PHONY : src/Visualizer.s

# target to generate assembly for a file
src/Visualizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/Visualizer.cpp.s
.PHONY : src/Visualizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir.dir/build.make CMakeFiles/mimir.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir.dir/build.make CMakeFiles/mimir.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir.dir/build.make CMakeFiles/mimir.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/runtimes/AbstractRuntime.o: src/runtimes/AbstractRuntime.cpp.o
.PHONY : src/runtimes/AbstractRuntime.o

# target to build an object file
src/runtimes/AbstractRuntime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/AbstractRuntime.cpp.o
.PHONY : src/runtimes/AbstractRuntime.cpp.o

src/runtimes/AbstractRuntime.i: src/runtimes/AbstractRuntime.cpp.i
.PHONY : src/runtimes/AbstractRuntime.i

# target to preprocess a source file
src/runtimes/AbstractRuntime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/AbstractRuntime.cpp.i
.PHONY : src/runtimes/AbstractRuntime.cpp.i

src/runtimes/AbstractRuntime.s: src/runtimes/AbstractRuntime.cpp.s
.PHONY : src/runtimes/AbstractRuntime.s

# target to generate assembly for a file
src/runtimes/AbstractRuntime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/AbstractRuntime.cpp.s
.PHONY : src/runtimes/AbstractRuntime.cpp.s

src/runtimes/LayerOps.o: src/runtimes/LayerOps.cpp.o
.PHONY : src/runtimes/LayerOps.o

# target to build an object file
src/runtimes/LayerOps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/LayerOps.cpp.o
.PHONY : src/runtimes/LayerOps.cpp.o

src/runtimes/LayerOps.i: src/runtimes/LayerOps.cpp.i
.PHONY : src/runtimes/LayerOps.i

# target to preprocess a source file
src/runtimes/LayerOps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/LayerOps.cpp.i
.PHONY : src/runtimes/LayerOps.cpp.i

src/runtimes/LayerOps.s: src/runtimes/LayerOps.cpp.s
.PHONY : src/runtimes/LayerOps.s

# target to generate assembly for a file
src/runtimes/LayerOps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/LayerOps.cpp.s
.PHONY : src/runtimes/LayerOps.cpp.s

src/runtimes/RuntimeRouter.o: src/runtimes/RuntimeRouter.cpp.o
.PHONY : src/runtimes/RuntimeRouter.o

# target to build an object file
src/runtimes/RuntimeRouter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/RuntimeRouter.cpp.o
.PHONY : src/runtimes/RuntimeRouter.cpp.o

src/runtimes/RuntimeRouter.i: src/runtimes/RuntimeRouter.cpp.i
.PHONY : src/runtimes/RuntimeRouter.i

# target to preprocess a source file
src/runtimes/RuntimeRouter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/RuntimeRouter.cpp.i
.PHONY : src/runtimes/RuntimeRouter.cpp.i

src/runtimes/RuntimeRouter.s: src/runtimes/RuntimeRouter.cpp.s
.PHONY : src/runtimes/RuntimeRouter.s

# target to generate assembly for a file
src/runtimes/RuntimeRouter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/RuntimeRouter.cpp.s
.PHONY : src/runtimes/RuntimeRouter.cpp.s

src/runtimes/cpu/CpuRuntime.o: src/runtimes/cpu/CpuRuntime.cpp.o
.PHONY : src/runtimes/cpu/CpuRuntime.o

# target to build an object file
src/runtimes/cpu/CpuRuntime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/cpu/CpuRuntime.cpp.o
.PHONY : src/runtimes/cpu/CpuRuntime.cpp.o

src/runtimes/cpu/CpuRuntime.i: src/runtimes/cpu/CpuRuntime.cpp.i
.PHONY : src/runtimes/cpu/CpuRuntime.i

# target to preprocess a source file
src/runtimes/cpu/CpuRuntime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/cpu/CpuRuntime.cpp.i
.PHONY : src/runtimes/cpu/CpuRuntime.cpp.i

src/runtimes/cpu/CpuRuntime.s: src/runtimes/cpu/CpuRuntime.cpp.s
.PHONY : src/runtimes/cpu/CpuRuntime.s

# target to generate assembly for a file
src/runtimes/cpu/CpuRuntime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/cpu/CpuRuntime.cpp.s
.PHONY : src/runtimes/cpu/CpuRuntime.cpp.s

src/runtimes/opencl/OpenCLRuntime.o: src/runtimes/opencl/OpenCLRuntime.cpp.o
.PHONY : src/runtimes/opencl/OpenCLRuntime.o

# target to build an object file
src/runtimes/opencl/OpenCLRuntime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/opencl/OpenCLRuntime.cpp.o
.PHONY : src/runtimes/opencl/OpenCLRuntime.cpp.o

src/runtimes/opencl/OpenCLRuntime.i: src/runtimes/opencl/OpenCLRuntime.cpp.i
.PHONY : src/runtimes/opencl/OpenCLRuntime.i

# target to preprocess a source file
src/runtimes/opencl/OpenCLRuntime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/opencl/OpenCLRuntime.cpp.i
.PHONY : src/runtimes/opencl/OpenCLRuntime.cpp.i

src/runtimes/opencl/OpenCLRuntime.s: src/runtimes/opencl/OpenCLRuntime.cpp.s
.PHONY : src/runtimes/opencl/OpenCLRuntime.s

# target to generate assembly for a file
src/runtimes/opencl/OpenCLRuntime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/opencl/OpenCLRuntime.cpp.s
.PHONY : src/runtimes/opencl/OpenCLRuntime.cpp.s

src/runtimes/ops_loss_and_grad.o: src/runtimes/ops_loss_and_grad.cpp.o
.PHONY : src/runtimes/ops_loss_and_grad.o

# target to build an object file
src/runtimes/ops_loss_and_grad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/ops_loss_and_grad.cpp.o
.PHONY : src/runtimes/ops_loss_and_grad.cpp.o

src/runtimes/ops_loss_and_grad.i: src/runtimes/ops_loss_and_grad.cpp.i
.PHONY : src/runtimes/ops_loss_and_grad.i

# target to preprocess a source file
src/runtimes/ops_loss_and_grad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/ops_loss_and_grad.cpp.i
.PHONY : src/runtimes/ops_loss_and_grad.cpp.i

src/runtimes/ops_loss_and_grad.s: src/runtimes/ops_loss_and_grad.cpp.s
.PHONY : src/runtimes/ops_loss_and_grad.s

# target to generate assembly for a file
src/runtimes/ops_loss_and_grad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/ops_loss_and_grad.cpp.s
.PHONY : src/runtimes/ops_loss_and_grad.cpp.s

src/runtimes/vulkan/VulkanRuntime.o: src/runtimes/vulkan/VulkanRuntime.cpp.o
.PHONY : src/runtimes/vulkan/VulkanRuntime.o

# target to build an object file
src/runtimes/vulkan/VulkanRuntime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/vulkan/VulkanRuntime.cpp.o
.PHONY : src/runtimes/vulkan/VulkanRuntime.cpp.o

src/runtimes/vulkan/VulkanRuntime.i: src/runtimes/vulkan/VulkanRuntime.cpp.i
.PHONY : src/runtimes/vulkan/VulkanRuntime.i

# target to preprocess a source file
src/runtimes/vulkan/VulkanRuntime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/vulkan/VulkanRuntime.cpp.i
.PHONY : src/runtimes/vulkan/VulkanRuntime.cpp.i

src/runtimes/vulkan/VulkanRuntime.s: src/runtimes/vulkan/VulkanRuntime.cpp.s
.PHONY : src/runtimes/vulkan/VulkanRuntime.s

# target to generate assembly for a file
src/runtimes/vulkan/VulkanRuntime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/runtimes/vulkan/VulkanRuntime.cpp.s
.PHONY : src/runtimes/vulkan/VulkanRuntime.cpp.s

src/scriptings/CSharp/csharpScripting/CSharpScripting.o: src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.o
.PHONY : src/scriptings/CSharp/csharpScripting/CSharpScripting.o

# target to build an object file
src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.o
.PHONY : src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.o

src/scriptings/CSharp/csharpScripting/CSharpScripting.i: src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.i
.PHONY : src/scriptings/CSharp/csharpScripting/CSharpScripting.i

# target to preprocess a source file
src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.i
.PHONY : src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.i

src/scriptings/CSharp/csharpScripting/CSharpScripting.s: src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.s
.PHONY : src/scriptings/CSharp/csharpScripting/CSharpScripting.s

# target to generate assembly for a file
src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.s
.PHONY : src/scriptings/CSharp/csharpScripting/CSharpScripting.cpp.s

src/scriptings/JavaScript/jsScripting/JSScripting.o: src/scriptings/JavaScript/jsScripting/JSScripting.cpp.o
.PHONY : src/scriptings/JavaScript/jsScripting/JSScripting.o

# target to build an object file
src/scriptings/JavaScript/jsScripting/JSScripting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/JavaScript/jsScripting/JSScripting.cpp.o
.PHONY : src/scriptings/JavaScript/jsScripting/JSScripting.cpp.o

src/scriptings/JavaScript/jsScripting/JSScripting.i: src/scriptings/JavaScript/jsScripting/JSScripting.cpp.i
.PHONY : src/scriptings/JavaScript/jsScripting/JSScripting.i

# target to preprocess a source file
src/scriptings/JavaScript/jsScripting/JSScripting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/JavaScript/jsScripting/JSScripting.cpp.i
.PHONY : src/scriptings/JavaScript/jsScripting/JSScripting.cpp.i

src/scriptings/JavaScript/jsScripting/JSScripting.s: src/scriptings/JavaScript/jsScripting/JSScripting.cpp.s
.PHONY : src/scriptings/JavaScript/jsScripting/JSScripting.s

# target to generate assembly for a file
src/scriptings/JavaScript/jsScripting/JSScripting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/JavaScript/jsScripting/JSScripting.cpp.s
.PHONY : src/scriptings/JavaScript/jsScripting/JSScripting.cpp.s

src/scriptings/Lua/luaScripting/LuaScripting.o: src/scriptings/Lua/luaScripting/LuaScripting.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScripting.o

# target to build an object file
src/scriptings/Lua/luaScripting/LuaScripting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScripting.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScripting.cpp.o

src/scriptings/Lua/luaScripting/LuaScripting.i: src/scriptings/Lua/luaScripting/LuaScripting.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScripting.i

# target to preprocess a source file
src/scriptings/Lua/luaScripting/LuaScripting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScripting.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScripting.cpp.i

src/scriptings/Lua/luaScripting/LuaScripting.s: src/scriptings/Lua/luaScripting/LuaScripting.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScripting.s

# target to generate assembly for a file
src/scriptings/Lua/luaScripting/LuaScripting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScripting.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScripting.cpp.s

src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.o: src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.o

# target to build an object file
src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.o

src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.i: src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.i

# target to preprocess a source file
src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.i

src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.s: src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.s

# target to generate assembly for a file
src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.cpp.s

src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.o: src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.o

# target to build an object file
src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.o

src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.i: src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.i

# target to preprocess a source file
src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.i

src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.s: src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.s

# target to generate assembly for a file
src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.cpp.s

src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.o: src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.o

# target to build an object file
src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.o
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.o

src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.i: src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.i

# target to preprocess a source file
src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.i
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.i

src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.s: src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.s

# target to generate assembly for a file
src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.s
.PHONY : src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.cpp.s

src/scriptings/Rust/rustScripting/RustScripting.o: src/scriptings/Rust/rustScripting/RustScripting.cpp.o
.PHONY : src/scriptings/Rust/rustScripting/RustScripting.o

# target to build an object file
src/scriptings/Rust/rustScripting/RustScripting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Rust/rustScripting/RustScripting.cpp.o
.PHONY : src/scriptings/Rust/rustScripting/RustScripting.cpp.o

src/scriptings/Rust/rustScripting/RustScripting.i: src/scriptings/Rust/rustScripting/RustScripting.cpp.i
.PHONY : src/scriptings/Rust/rustScripting/RustScripting.i

# target to preprocess a source file
src/scriptings/Rust/rustScripting/RustScripting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Rust/rustScripting/RustScripting.cpp.i
.PHONY : src/scriptings/Rust/rustScripting/RustScripting.cpp.i

src/scriptings/Rust/rustScripting/RustScripting.s: src/scriptings/Rust/rustScripting/RustScripting.cpp.s
.PHONY : src/scriptings/Rust/rustScripting/RustScripting.s

# target to generate assembly for a file
src/scriptings/Rust/rustScripting/RustScripting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/Rust/rustScripting/RustScripting.cpp.s
.PHONY : src/scriptings/Rust/rustScripting/RustScripting.cpp.s

src/scriptings/ScriptingBridgeCommon.o: src/scriptings/ScriptingBridgeCommon.cpp.o
.PHONY : src/scriptings/ScriptingBridgeCommon.o

# target to build an object file
src/scriptings/ScriptingBridgeCommon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/ScriptingBridgeCommon.cpp.o
.PHONY : src/scriptings/ScriptingBridgeCommon.cpp.o

src/scriptings/ScriptingBridgeCommon.i: src/scriptings/ScriptingBridgeCommon.cpp.i
.PHONY : src/scriptings/ScriptingBridgeCommon.i

# target to preprocess a source file
src/scriptings/ScriptingBridgeCommon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/ScriptingBridgeCommon.cpp.i
.PHONY : src/scriptings/ScriptingBridgeCommon.cpp.i

src/scriptings/ScriptingBridgeCommon.s: src/scriptings/ScriptingBridgeCommon.cpp.s
.PHONY : src/scriptings/ScriptingBridgeCommon.s

# target to generate assembly for a file
src/scriptings/ScriptingBridgeCommon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/scriptings/ScriptingBridgeCommon.cpp.s
.PHONY : src/scriptings/ScriptingBridgeCommon.cpp.s

src/stb_image_impl.o: src/stb_image_impl.cpp.o
.PHONY : src/stb_image_impl.o

# target to build an object file
src/stb_image_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/stb_image_impl.cpp.o
.PHONY : src/stb_image_impl.cpp.o

src/stb_image_impl.i: src/stb_image_impl.cpp.i
.PHONY : src/stb_image_impl.i

# target to preprocess a source file
src/stb_image_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/stb_image_impl.cpp.i
.PHONY : src/stb_image_impl.cpp.i

src/stb_image_impl.s: src/stb_image_impl.cpp.s
.PHONY : src/stb_image_impl.s

# target to generate assembly for a file
src/stb_image_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/stb_image_impl.cpp.s
.PHONY : src/stb_image_impl.cpp.s

src/tensors.o: src/tensors.cpp.o
.PHONY : src/tensors.o

# target to build an object file
src/tensors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/tensors.cpp.o
.PHONY : src/tensors.cpp.o

src/tensors.i: src/tensors.cpp.i
.PHONY : src/tensors.i

# target to preprocess a source file
src/tensors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/tensors.cpp.i
.PHONY : src/tensors.cpp.i

src/tensors.s: src/tensors.cpp.s
.PHONY : src/tensors.s

# target to generate assembly for a file
src/tensors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimir_core.dir/build.make CMakeFiles/mimir_core.dir/src/tensors.cpp.s
.PHONY : src/tensors.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... appimage"
	@echo "... mimir_shaders"
	@echo "... mimir"
	@echo "... mimir_core"
	@echo "... src/ConfigOverrides.o"
	@echo "... src/ConfigOverrides.i"
	@echo "... src/ConfigOverrides.s"
	@echo "... src/Encoder.o"
	@echo "... src/Encoder.i"
	@echo "... src/Encoder.s"
	@echo "... src/Helpers.o"
	@echo "... src/Helpers.i"
	@echo "... src/Helpers.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Models/Diffusion/CondDiffusionModel.o"
	@echo "... src/Models/Diffusion/CondDiffusionModel.i"
	@echo "... src/Models/Diffusion/CondDiffusionModel.s"
	@echo "... src/Models/Diffusion/DiffusionModel.o"
	@echo "... src/Models/Diffusion/DiffusionModel.i"
	@echo "... src/Models/Diffusion/DiffusionModel.s"
	@echo "... src/Models/Diffusion/HFSDXLTransformerBlockModel.o"
	@echo "... src/Models/Diffusion/HFSDXLTransformerBlockModel.i"
	@echo "... src/Models/Diffusion/HFSDXLTransformerBlockModel.s"
	@echo "... src/Models/Diffusion/LumenLatentDiffusionModel.o"
	@echo "... src/Models/Diffusion/LumenLatentDiffusionModel.i"
	@echo "... src/Models/Diffusion/LumenLatentDiffusionModel.s"
	@echo "... src/Models/Diffusion/SD35Model.o"
	@echo "... src/Models/Diffusion/SD35Model.i"
	@echo "... src/Models/Diffusion/SD35Model.s"
	@echo "... src/Models/External/ExternalSafeTensorsModel.o"
	@echo "... src/Models/External/ExternalSafeTensorsModel.i"
	@echo "... src/Models/External/ExternalSafeTensorsModel.s"
	@echo "... src/Models/MLP/BasicMLPModel.o"
	@echo "... src/Models/MLP/BasicMLPModel.i"
	@echo "... src/Models/MLP/BasicMLPModel.s"
	@echo "... src/Models/NLP/CausalLMModel.o"
	@echo "... src/Models/NLP/CausalLMModel.i"
	@echo "... src/Models/NLP/CausalLMModel.s"
	@echo "... src/Models/NLP/HFCLIPTextEncoder1Model.o"
	@echo "... src/Models/NLP/HFCLIPTextEncoder1Model.i"
	@echo "... src/Models/NLP/HFCLIPTextEncoder1Model.s"
	@echo "... src/Models/NLP/HFCLIPTextEncoder2Model.o"
	@echo "... src/Models/NLP/HFCLIPTextEncoder2Model.i"
	@echo "... src/Models/NLP/HFCLIPTextEncoder2Model.s"
	@echo "... src/Models/NLP/TransformerModel.o"
	@echo "... src/Models/NLP/TransformerModel.i"
	@echo "... src/Models/NLP/TransformerModel.s"
	@echo "... src/Models/NLP/VAETextModel.o"
	@echo "... src/Models/NLP/VAETextModel.i"
	@echo "... src/Models/NLP/VAETextModel.s"
	@echo "... src/Models/Registry/ModelArchitectures.o"
	@echo "... src/Models/Registry/ModelArchitectures.i"
	@echo "... src/Models/Registry/ModelArchitectures.s"
	@echo "... src/Models/Vision/CNN/MobileNetModel.o"
	@echo "... src/Models/Vision/CNN/MobileNetModel.i"
	@echo "... src/Models/Vision/CNN/MobileNetModel.s"
	@echo "... src/Models/Vision/CNN/ResNetModel.o"
	@echo "... src/Models/Vision/CNN/ResNetModel.i"
	@echo "... src/Models/Vision/CNN/ResNetModel.s"
	@echo "... src/Models/Vision/CNN/VGG16FeatModel.o"
	@echo "... src/Models/Vision/CNN/VGG16FeatModel.i"
	@echo "... src/Models/Vision/CNN/VGG16FeatModel.s"
	@echo "... src/Models/Vision/CNN/VGG16Model.o"
	@echo "... src/Models/Vision/CNN/VGG16Model.i"
	@echo "... src/Models/Vision/CNN/VGG16Model.s"
	@echo "... src/Models/Vision/CNN/VGG19Model.o"
	@echo "... src/Models/Vision/CNN/VGG19Model.i"
	@echo "... src/Models/Vision/CNN/VGG19Model.s"
	@echo "... src/Models/Vision/GanLatentModel.o"
	@echo "... src/Models/Vision/GanLatentModel.i"
	@echo "... src/Models/Vision/GanLatentModel.s"
	@echo "... src/Models/Vision/HFVaeDecoderModel.o"
	@echo "... src/Models/Vision/HFVaeDecoderModel.i"
	@echo "... src/Models/Vision/HFVaeDecoderModel.s"
	@echo "... src/Models/Vision/PatchDiscriminatorModel.o"
	@echo "... src/Models/Vision/PatchDiscriminatorModel.i"
	@echo "... src/Models/Vision/PatchDiscriminatorModel.s"
	@echo "... src/Models/Vision/UNetModel.o"
	@echo "... src/Models/Vision/UNetModel.i"
	@echo "... src/Models/Vision/UNetModel.s"
	@echo "... src/Models/Vision/VAEConvModel.o"
	@echo "... src/Models/Vision/VAEConvModel.i"
	@echo "... src/Models/Vision/VAEConvModel.s"
	@echo "... src/Models/Vision/VAEModel.o"
	@echo "... src/Models/Vision/VAEModel.i"
	@echo "... src/Models/Vision/VAEModel.s"
	@echo "... src/Models/Vision/ViTModel.o"
	@echo "... src/Models/Vision/ViTModel.i"
	@echo "... src/Models/Vision/ViTModel.s"
	@echo "... src/Serialization/DebugJsonDump.o"
	@echo "... src/Serialization/DebugJsonDump.i"
	@echo "... src/Serialization/DebugJsonDump.s"
	@echo "... src/Serialization/RawCheckpointReader.o"
	@echo "... src/Serialization/RawCheckpointReader.i"
	@echo "... src/Serialization/RawCheckpointReader.s"
	@echo "... src/Serialization/RawCheckpointWriter.o"
	@echo "... src/Serialization/RawCheckpointWriter.i"
	@echo "... src/Serialization/RawCheckpointWriter.s"
	@echo "... src/Serialization/SafeTensorsReader.o"
	@echo "... src/Serialization/SafeTensorsReader.i"
	@echo "... src/Serialization/SafeTensorsReader.s"
	@echo "... src/Serialization/SafeTensorsWriter.o"
	@echo "... src/Serialization/SafeTensorsWriter.i"
	@echo "... src/Serialization/SafeTensorsWriter.s"
	@echo "... src/Serialization/Serialization.o"
	@echo "... src/Serialization/Serialization.i"
	@echo "... src/Serialization/Serialization.s"
	@echo "... src/Sha256.o"
	@echo "... src/Sha256.i"
	@echo "... src/Sha256.s"
	@echo "... src/Tokenizer.o"
	@echo "... src/Tokenizer.i"
	@echo "... src/Tokenizer.s"
	@echo "... src/Visualizer.o"
	@echo "... src/Visualizer.i"
	@echo "... src/Visualizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/runtimes/AbstractRuntime.o"
	@echo "... src/runtimes/AbstractRuntime.i"
	@echo "... src/runtimes/AbstractRuntime.s"
	@echo "... src/runtimes/LayerOps.o"
	@echo "... src/runtimes/LayerOps.i"
	@echo "... src/runtimes/LayerOps.s"
	@echo "... src/runtimes/RuntimeRouter.o"
	@echo "... src/runtimes/RuntimeRouter.i"
	@echo "... src/runtimes/RuntimeRouter.s"
	@echo "... src/runtimes/cpu/CpuRuntime.o"
	@echo "... src/runtimes/cpu/CpuRuntime.i"
	@echo "... src/runtimes/cpu/CpuRuntime.s"
	@echo "... src/runtimes/opencl/OpenCLRuntime.o"
	@echo "... src/runtimes/opencl/OpenCLRuntime.i"
	@echo "... src/runtimes/opencl/OpenCLRuntime.s"
	@echo "... src/runtimes/ops_loss_and_grad.o"
	@echo "... src/runtimes/ops_loss_and_grad.i"
	@echo "... src/runtimes/ops_loss_and_grad.s"
	@echo "... src/runtimes/vulkan/VulkanRuntime.o"
	@echo "... src/runtimes/vulkan/VulkanRuntime.i"
	@echo "... src/runtimes/vulkan/VulkanRuntime.s"
	@echo "... src/scriptings/CSharp/csharpScripting/CSharpScripting.o"
	@echo "... src/scriptings/CSharp/csharpScripting/CSharpScripting.i"
	@echo "... src/scriptings/CSharp/csharpScripting/CSharpScripting.s"
	@echo "... src/scriptings/JavaScript/jsScripting/JSScripting.o"
	@echo "... src/scriptings/JavaScript/jsScripting/JSScripting.i"
	@echo "... src/scriptings/JavaScript/jsScripting/JSScripting.s"
	@echo "... src/scriptings/Lua/luaScripting/LuaScripting.o"
	@echo "... src/scriptings/Lua/luaScripting/LuaScripting.i"
	@echo "... src/scriptings/Lua/luaScripting/LuaScripting.s"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.o"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.i"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingModelAndRegistry.s"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.o"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.i"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingRuntimeAndViz.s"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.o"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.i"
	@echo "... src/scriptings/Lua/luaScripting/LuaScriptingTokenizerDataset.s"
	@echo "... src/scriptings/Rust/rustScripting/RustScripting.o"
	@echo "... src/scriptings/Rust/rustScripting/RustScripting.i"
	@echo "... src/scriptings/Rust/rustScripting/RustScripting.s"
	@echo "... src/scriptings/ScriptingBridgeCommon.o"
	@echo "... src/scriptings/ScriptingBridgeCommon.i"
	@echo "... src/scriptings/ScriptingBridgeCommon.s"
	@echo "... src/stb_image_impl.o"
	@echo "... src/stb_image_impl.i"
	@echo "... src/stb_image_impl.s"
	@echo "... src/tensors.o"
	@echo "... src/tensors.i"
	@echo "... src/tensors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

