#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer InABuf {
    float a_data[];
};

layout(std430, binding = 1) readonly buffer InBBuf {
    float b_data[];
};

layout(std430, binding = 2) writeonly buffer OutBuf {
    float out_data[];
};

layout(push_constant) uniform Dims {
    uint n;
} pc;

void main() {
    const uint i = gl_GlobalInvocationID.x;
    if (i >= pc.n) return;
    out_data[i] = a_data[i] * b_data[i];
}
