-- Explicit CLI documentation, shared renderer in help_cli.lua.
local Help = dofile(ROOTWORK.."/scripts/modules/help_cli.lua")
local specs = {
  ["convert_checkpoint2safetensor"] = {
    script_path = "scripts/tools/convert_checkpoint2safetensor.lua",
    description = "Convertir un checkpoint RawFolder en SafeTensors, avec reconstruction du modèle.",
    options = {
      "--checkpoint <dossier>, --in <dossier>  Checkpoint source obligatoire",
      "--out <fichier>  Sortie (défaut : chemin source suffixé .safetensors)",
      "--model-type <nom>, --model <nom>  Type du modèle (défaut : inféré depuis architecture.json)",
      "--mem-gb <n>  Limite MemoryGuard en Go (défaut : 8)",
      "--alloc-gb <n>  Budget allocateur en Go (défaut : 8)",
      "--compression / --no-compression  Compression mémoire (défaut : activée)",
      "--hw / --no-hw  Accélération matérielle (défaut : désactivée)",
    },
    examples = {
      "./bin/mimir --lua scripts/tools/convert_checkpoint2safetensor.lua -- --checkpoint checkpoints/run --out exports/model.safetensors",
    },
  },
  ["convert_safetensors2raw_folder"] = {
    script_path = "scripts/tools/convert_safetensors2raw_folder.lua",
    description = "Convertir un checkpoint SafeTensors Mímir en dossier RawFolder.",
    options = {
      "--in <fichier>, --checkpoint <fichier>  Source obligatoire",
      "--out <dossier>, --out-dir <dossier>  Destination obligatoire",
      "--mem-gb <n>  Limite MemoryGuard en Go (défaut : 8)",
      "--alloc-gb <n>  Budget allocateur en Go (défaut : 8)",
      "--compression / --no-compression  Compression mémoire (défaut : activée)",
      "--hw / --no-hw  Accélération matérielle (défaut : désactivée)",
    },
    examples = {
      "./bin/mimir --lua scripts/tools/convert_safetensors2raw_folder.lua -- --in exports/model.safetensors --out checkpoints/converted",
    },
  },
  ["inspect_z_prior_raw_folder"] = {
    script_path = "scripts/tools/inspect_z_prior_raw_folder.lua",
    description = "Inspecter le tenseur z_prior d’un checkpoint RawFolder et exporter ses valeurs ou images.",
    options = {
      "--checkpoint <dossier>, --in <dossier>  Checkpoint obligatoire",
      "--tensor <nom>  Tenseur explicite (défaut : recherche de z_prior)",
      "--max-values <n>  Valeurs affichées (défaut : 128, minimum : 1)",
      "--topk <n>  Nombre de valeurs extrêmes (défaut : 16, minimum : 1)",
      "--out <fichier.csv>  Export CSV facultatif",
      "--image-out <fichier>  Image PPM (défaut : <checkpoint>/z_prior_feature_map.ppm)",
      "--hist-out <fichier>  Histogramme PPM (défaut : <checkpoint>/z_prior_histogram.ppm)",
      "--image-width <n>  Largeur image (défaut : 0, automatique)",
      "--hist-bins <n>  Classes de l’histogramme (défaut : 128, minimum : 8)",
      "--hist-width <n>  Largeur histogramme (défaut : 960, minimum : 320)",
      "--hist-height <n>  Hauteur histogramme (défaut : 420, minimum : 220)",
      "--quiet / --no-quiet  Affichage réduit (défaut : false)",
    },
    examples = {
      "./bin/mimir --lua scripts/tools/inspect_z_prior_raw_folder.lua -- --checkpoint checkpoints/run --max-values 32",
      "./bin/mimir --lua scripts/tools/inspect_z_prior_raw_folder.lua -- --checkpoint checkpoints/run --out exports/z_prior.csv",
    },
  },
  ["analyze_model"] = {
    script_path = "scripts/tools/analyze_model.lua",
    description = "Analyser un checkpoint RawFolder, SafeTensors (.st accepté) ou DebugJSON : couches, tenseurs et graphes.",
    options = {
      "--in <path>                         Chemin du modèle (requis)",
      "--max-layers <n>                    Limite l'affichage des couches / graphe",
      "--top-tensors <n>                   Nb de tensors listés (par taille)",
      "--enrich-tensors <n>                [RawFolder] enrichit les N plus gros tensors (dtype/shape)",
      "--graph-format <table|blocks|mermaid|mlp_graph|visu-bloc|visu-tree>  Défaut : table ; alias visu=visu-bloc, mermaind=mermaid",
      "--graph-out <path.{svg|png|jpg}>    Exporte le graphe Mermaid vers un fichier image",
      "--graph-blocks <bool>               Affiche le graphe 'blocks' en plus du graphe principal (défaut: false)",
      "--graph-in-width <n>                Largeur inputs (mode blocks)",
      "--graph-layer-width <n>             Largeur layer (mode blocks)",
      "--graph-out-width <n>               Largeur output (mode blocks)",
      "--graph-units <n>                   Neurones/canaux visibles par couche (visu-tree, défaut: 8, max: 32)",
      "--all <bool>                        Affiche toutes les valeurs sans troncature dans l'entête (sur plusieurs lignes si besoin) (défaut: false)",
      "--debug <bool>                      Logs de debug (défaut: false)",
      "--script-help <bool>                Affiche cette aide (alias: --help-script, --h)",
      "--path <chemin>, --checkpoint <chemin>  Alias de --in",
      "Les options composées acceptent aussi les alias avec underscores (ex. --max_layers).",
      "Défauts : top-tensors=20, enrich-tensors=25, max-layers et largeurs non imposés.",
      "Export image : Mermaid CLI (mmdc) requis ; ImageMagick également pour JPG.",
    },
    examples = {
      "./bin/mimir --lua scripts/tools/analyze_model.lua -- --in model.safetensors --top-tensors 10",
      "./bin/mimir --lua scripts/tools/analyze_model.lua -- --in checkpoints/run --graph-format mermaid",
    },
  },
  ["inspect_architectures"] = {
    script_path = "scripts/tools/inspect_architectures.lua",
    description = "Inspecter le registre, les couches, les types numériques et les capacités runtime ; exporter une architecture.",
    options = {
      "-a, --show-archs Liste les architectures disponibles (+ dtypes)",
      "-l, --list <arch> Sélectionne une architecture par son nom",
      "-e, --export <path> Exporte l'architecture sélectionnée",
      "-p, --params Affiche les paramètres de l'archi sélectionnée",
      "--layers Affiche les layers de l'archi sélectionnée",
      "--stats Affiche les statistiques théoriques (params par layer)",
      "--ops Inventorie les layer types / ops présents dans les graphes",
      "--ops-compact Vue compacte de --ops, regroupée par famille",
      "--runtime Affiche les capacités runtime exposées au Lua API",
      "-d, --dtypes Liste les dtypes pris en charge par le framework",
      "--optimizers Liste les algorithmes d'optimisation disponibles",
      "--recon-losses Liste les fonctions de reconstruction disponibles",
      "--json Export JSON complet du registre",
      "--compact  Alias de --ops-compact",
      "Export : .json → DebugJSON ; .safetensors → SafeTensors ; dossier → RawFolder.",
    },
    examples = {
      "./bin/mimir --lua scripts/tools/inspect_architectures.lua -- --show-archs",
      "./bin/mimir --lua scripts/tools/inspect_architectures.lua -- --list vae_conv --layers --stats",
      "./bin/mimir --lua scripts/tools/inspect_architectures.lua -- --list transformer --export exports/transformer.json",
    },
  },
  ["show-graph"] = {
    script_path = "scripts/tools/show-graph.lua",
    description = "Générer un rapport HTML interactif des métriques et des rapports Markdown/TXT ; surveillance optionnelle.",
    options = {
      "[CSV]                    CSV (défaut: checkpoints/loss_history.csv)",
      "--csv PATH               Alias (idem que positional)",
      "--csv-dir DIR            Dossier contenant des CSV *part[0-9].csv à fusionner",
      "--model NAME             Nom du modèle",
      "--algo NAME              Algorithme d'optimisation (alias de --optimizer)",
      "--optimizer NAME         Algorithme d'optimisation (adamw, adam, sgd, ...)",
      "--recon-loss NAME        Fonction de reconstruction (mse, l1, charbonnier, ...)",
      "--checkpoint PATH        Dossier checkpoint ou fichier DEBUGJSON Mímir",
      "--checkpoint-dir PATH    Alias rétrocompatible de --checkpoint",
      "-n, --no-interactive     Pas de prompts stdin",
      "--out PATH               HTML de sortie (défaut: ./graph_report.html)",
      "--out-text PATH          Rapport .md/.txt; rapport.{md,txt} génère les deux",
      "--watch                  Surveille le CSV et régénère le rapport à chaque changement",
      "--watch-interval N       Intervalle de polling en secondes (défaut: 2)",
      "--validate-every-steps N Fréquence de validation (en opt_steps) — auto-détecté si absent",
      "--validate-items N       Nombre d'images évaluées par validation — auto-détecté si absent",
      "--n-dataset N            Taille du dataset (items par epoch) — auto-détecté si absent",
    },
    examples = {
      "./bin/mimir --lua scripts/tools/show-graph.lua -- --csv loss_history.csv --no-interactive --out report.html --out-text \"rapport.{md,txt}\"",
      "./bin/mimir --lua scripts/tools/show-graph.lua -- --csv-dir checkpoints/run --watch --watch-interval 2",
    },
  },
  ["build_tags_vocab"] = {
    script_path = "scripts/tools/build_tags_vocab.lua",
    description = "Construire un vocabulaire depuis TXT, COCO, VinDr-Mammo ou MVinDr ; peut préparer les paires image/texte.",
    options = {
      "--dataset-root <valeur>  Racine des annotations (défaut : dataset_2)",
      "--out <valeur>  Vocabulaire de sortie (un token par ligne) (défaut : checkpoint/tags_vocab.txt)",
      "--lowercase / --no-lowercase  Convertir en minuscules (défaut : true)",
      "--min-freq <valeur>  Fréquence minimale (défaut : 1)",
      "--top-k <valeur>  Nombre maximal de tags (0 : sans limite) (défaut : 0)",
      "--max-files <valeur>  Nombre maximal de fichiers (0 : sans limite) (défaut : 0)",
      "--coco-annotations <valeur>  JSON COCO explicite (sinon détection)",
      "--composition-out <valeur>  Rapport de composition (défaut : chemin --out avec extension .composition.json)",
      "--vindr-breast-annotations <valeur>  CSV des annotations mammaires (sinon détection)",
      "--vindr-finding-annotations <valeur>  CSV des observations (sinon détection)",
      "--vindr-images-root <valeur>  Racine des images (sinon détection)",
      "--vindr-prepared-root <valeur>  Dossier des paires image/texte préparées (sinon valeur calculée)",
      "--vindr-dicom-converter <valeur>  Commande du convertisseur DICOM",
      "--mvindr-manifest <valeur>  Manifest CSV MVinDr (sinon détection)",
      "--mvindr-mask-tags / --no-mvindr-mask-tags  Ajouter les tags issus des masques (défaut : true)",
      "--mvindr-small-max <valeur>  Seuil maximal du ratio de surface pour une petite masse (défaut : 0.005)",
      "--mvindr-large-min <valeur>  Seuil minimal du ratio de surface pour une grande masse (défaut : 0.02)",
      "--dataset-format <valeur>  Format auto|txt|coco|vindr-mammo|mvindr-mass (alias vindr et mvindr ;défaut : auto)",
      "--split-mode <valeur>  Découpage auto|phrases|tokens|both (défaut : auto)",
      "--vindr-split <valeur>  Partition training|test|all (défaut : training)",
      "--vindr-labels <valeur>  Labels findings|diagnostic|all (défaut : all)",
      "--vindr-image-mode <valeur>  Préparation auto|copy|symlink|convert (défaut : auto)",
    },
    examples = {
      "./bin/mimir --lua scripts/tools/build_tags_vocab.lua -- --dataset-root dataset_2 --out exports/tags.txt --min-freq 2 --top-k 5000",
    },
  },
}
local M = {}
function M.show(name) Help.auto_exit_help(assert(specs[name])) end
function M.print(name) Help.print_help(assert(specs[name])) end
return M
